name: "unlock-luks-ssh"
description: "Unlock Linux systems during pre-boot (dropbear-initramfs)"
url: "https://github.com/majes-git/unlock-luks-ssh"
version: "2.0.0"
slug: "unlock-luks-ssh"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
schema:
  hosts:
    - name: str
      port: "int?"
      passphrase: str
      enabled: bool
options:
  hosts:
    - name: server.example.com
      passphrase: secret
      enabled: False
